server:
  port: 8096
spring:
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/as-ibrs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:as}
    password: ${MYSQL_PASSWORD:aswl.Com@db}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 500
        max-wait: 10000
        time-between-eviction-runs: 300000
      shutdown-timeout: 1000
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:aswl}
    password: ${RABBITMQ_DEFAULT_PASS:aswl.Com}
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:8085}/admin
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:11}
        instance:
          service-base-url: http://${USER_SERVICE_HOST:localhost}:${server.port}
          metadata:
            tags:
              environment: prd
  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址
    sender:
      type: web
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: $2a$10$S84wOzmAw4wqYBzAqNtmPOx1ZRWdDl9omm/W8T1hhW8S9EK2u57xG
      access-token-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/user/v1/user/info
      prefer-token-info: false
      jwt:
        key-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSawA+NUNmhB2ctiVnt
          YH41WCNoD5STW2iPm5AIsKvm6X67lr6A88qOMRwx9oySdZnUnJ+8L3QJ51fkwuDe
          ix5w9yA3f/7LUPWZU8M/7Oi+2nda05JMgU999TUlhTGsp9SPiBqq/iwuqMxU8xKu
          F8bpTJTOpzrxH4e5BM6J/UJcOwDZLY6/3zP5w+tbhTvxjc995G4NtUyS4owE1MHe
          lj8IJepknjePrE6nXD6ecdL401hstMY838UOOFiCnM8NpiBuNI0nY0qCbb9mhQZ+
          7gP3jjM+Ft7R+MFTuEHWQ5UN8qHAPIT9UlLcu9IXdk6YwTsqNavwaTLUcP/ih9HB
          6wIDAQAB
          -----END PUBLIC KEY-----

# mybatis配置
mybatis:
  type-aliases-package: com.aswl.as.ibrs.api.module
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ${FDFS_HOST:120.24.102.159}:${FDFS_PORT:22122}

# 系统配置
sys:
  adminUser: ${ADMIN_USER:admin}  # 管理员账号，默认是admin
  fdfsHttpHost: ${ATTACHMENT_HOST:http://120.24.102.159}  # fastDfs的HTTP配置
  uploadUrl: api/user/v1/attachment/upload
  defaultAvatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif?imageView2/1/w/80/h/80
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  output: rtmp://120.24.102.159/live/
  flvOutput: http://120.24.102.159:8768/live?port=1935&app=live&stream=
  projectCode: GZ-201911-001

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /hystrix.sender
    - /v1/sms/**
    - /v1/mobile/**
    - /v1/user/findUserByIdentifier/**
    - /v1/tenant/findTenantByTenantCode/**
    - /v1/menu/findMenuByRole/**
    - /v1/menu/findAllMenu
    - /v1/device/os/**
    - /v1/index/os/**
    - /v1/eventUcStatusGroup/os/**
    - /v1/region/os/**
    - /v1/contentIndustry/html/**
    - /v1/contentMalfunction/html/**
    - /v1/contentProduct/html/**
    - /v1/user/register
    - /v1/user/checkExist/**
    - /v1/user/updatePassword
    - /v1/userWatch/getUserAlarmType/**
    - /v1/code/**
    - /v1/attachment/download
    - /v1/log/**
    - /v1/regionLeader/getRegionLeaderByRegionId/**
    - /authentication/**
    - /v1/authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /bus/refresh
    - /v1/sys/file/**
    - /v1/region/meta/**
    - /v1/deviceMonitor/statusData/**
    - /v1/deviceMonitor/getOnlineStatusByDeviceId/**
    - /v1/device/deviceList
    - /v1/regionLeader/getRegionLeaderByPatrolKeyId/**
    - /v1/userWatch/getFavorite/**
    - /v1/qrcodeBatch/**
    - /dtu/message
    - /v1/regionLeader/**
    - /v1/project/**
    - /v1/userWatch/updateAlarmTypeUserFavorite
    - /v1/userWatch/findByUserId
    - /v1/alarmLevel/deleteByTenantCode
    - /v1/alarmOrderHandle/deleteByTenantCode
# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

logging:
  level:
    root: info
    com.aswl.as: debug
  #windows图片上传目录
file:
  path:
    winUpload: d:\\upload
  #linux图片上传目录
linuxfile:
    path:
      linuxUpload: /home/sftp/asms/web/upload

#发送邮件的邮箱设置
asmail:
  host: smtp.exmail.qq.com
  port: 465
  auth: true
  from: hr01@as-wl.com
  user: hr01@as-wl.com
  pass: 6qpyzYTYykq5EuFP
  isSmsMail: false
  debug: true
  sslEnable: true

#极光推送的账号密码
jpush:
  appKey: cdd96785a0ac47c9ebc0df5c
  masterSecret: 70434feda2ec94e757b4c5bd

#二维码重定向路径
qrcode:
   redirectUrl: http://192.168.200.216:8080/h5
#市级平台区域code和projectCode,市级平台Ip
cityPlatform:
  enable: false
  platform:
    isCityPlatform: true
    #cityName: 天河区
    #cityCode: A01A01A05
    #projectCode: bgsxm001
    #projectName: 办公室项目
    #ip: 192.168.200.240
    #rabbitUserName: aswl_test
    #rabbitPassword: aswl_Test
    #rabbitPort: 5672
sms:
  templateCode: SMS_213691411
  orderTemplateCode: SMS_227736238
  signName: 傲视物联