server:
  port: 8088
spring:
  application:
    name: iface-service
  datasource:
    url: jdbc:mysql://192.168.200.240:3306/as-ibrs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: aswl_dev
    password: aswl^Dev
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBIT_HOST:192.168.200.225}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:aswl_test}
    password: ${RABBITMQ_DEFAULT_PASS:aswl_Test}

# mybatis配置
mybatis:
  type-aliases-package: com.aswl.as.user.api.module
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# jwt的密钥和过期时间
jwt:
  config:
    key: gzaswl
    ttl: 1800000
#wsBaseParam:
#  serviceId: asid1568190091708
#  srcret: 123456

# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

# webSocket地址配置
socket:
  url: ws://localhost:8097/as-push
  send: /app/controlDevice