server:
  port: 8095
spring:
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/as-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:as}
    password: ${MYSQL_PASSWORD:aswl.Com@db}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:aswl}
    password: ${RABBITMQ_DEFAULT_PASS:aswl.Com}
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:8085}/admin
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:11}
        instance:
          service-base-url: http://${USER_SERVICE_HOST:localhost}:${server.port}
          metadata:
            tags:
              environment: prd
  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址
    sender:
      type: web
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: $2a$10$S84wOzmAw4wqYBzAqNtmPOx1ZRWdDl9omm/W8T1hhW8S9EK2u57xG
      access-token-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/user/v1/user/info
      prefer-token-info: false
      jwt:
        key-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8000}/api/auth/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSawA+NUNmhB2ctiVnt
          YH41WCNoD5STW2iPm5AIsKvm6X67lr6A88qOMRwx9oySdZnUnJ+8L3QJ51fkwuDe
          ix5w9yA3f/7LUPWZU8M/7Oi+2nda05JMgU999TUlhTGsp9SPiBqq/iwuqMxU8xKu
          F8bpTJTOpzrxH4e5BM6J/UJcOwDZLY6/3zP5w+tbhTvxjc995G4NtUyS4owE1MHe
          lj8IJepknjePrE6nXD6ecdL401hstMY838UOOFiCnM8NpiBuNI0nY0qCbb9mhQZ+
          7gP3jjM+Ft7R+MFTuEHWQ5UN8qHAPIT9UlLcu9IXdk6YwTsqNavwaTLUcP/ih9HB
          6wIDAQAB
          -----END PUBLIC KEY-----

# mybatis配置
mybatis:
  type-aliases-package: com.aswl.as.user.api.module
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ${FDFS_HOST:120.24.102.159}:${FDFS_PORT:22122}

# 系统配置
sys:
  adminUser: ${ADMIN_USER:admin}  # 管理员账号，默认是admin
  fdfsHttpHost: ${ATTACHMENT_HOST:http://120.24.102.159}  # fastDfs的HTTP配置
  uploadUrl: api/user/v1/attachment/upload
  defaultAvatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif?imageView2/1/w/80/h/80
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /hystrix.sender
    - /v1/sms/**
    - /v1/mobile/**
    - /v1/user/findUserByIdentifier/**
    - /v1/user/findUserByIdentifierForLogin/**
    - /v1/tenant/findTenantByTenantCode/**
    - /v1/tenant/os/**
    - /v1/config/isCloud
    - /v1/user/os/userList
    - /v1/menu/findMenuByRole/**
    - /v1/menu/findAllMenu
    - /v1/user/register
    - /v1/user/checkExist/**
    - /v1/user/updatePassword
    - /v1/user/findUserList
    - /v1/code/**
    - /v1/attachment/download
    - /v1/log/**
    - /authentication/**
    - /v1/authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /bus/refresh
    - /v1/user/findUserByIdentifierForLogin/**
    - /v1/config/isCloud
    - /v1/config/feign/**
    - /v1/user/checkTrialMobile
    - /v1/user/checkSmsCode
    - /v1/user/findPassword
    - /v1/user/registerUser
    - /v1/menu/menus
    - /v1/user/insertProjectAdminUser
    - /v1/user/getRoleId
    - /v1/user/deleteAll
    - /v1/user/sendNoticeUsers
    - /v1/user/sendEmailUsers
    - /v1/user/findUserByProjectId
    - /v1/user/updateInfo

# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

logging:
  level:
    root: info
    com.aswl.as: debug

# 短信配置
sms:
  appKey: ${SMS_APP_KEY:LTAI4GFF3zxX48bR7X2YyL65}
  appSecret: ${SMS_APP_SECRET:78FpD1OueNZr3iV9RLmKS7TL9jusBB}
  regionId: ${SMS_REGION_ID:default}
  domain: ${SMS_DOMAIN:dysmsapi.aliyuncs.com}
  signName: ${SMS_SIGN_NAME:安防通}
  templateCode: ${SMS_TEMP_CODE:SMS_204945143}
  version: ${SMS_VERSION:2017-05-25}
  action: ${SMS_ACTION:SendSms}

